-- 아이템의 희귀도가 'RARE'인 것들의 모든 다음 업그레이드 아이템 
-- 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)를 출력하는 SQL 문



SELECT ITEM_INFO.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE INNER JOIN ITEM_INFO
ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID

WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;
